[package]
name = "mothership-sidecar"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
mothership-core = { path = "../crates/mothership-core" }
process-sandbox = { path = "../crates/process-sandbox" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
